# Deploy to Azure Kubernetes Service
- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'Azure subscription 1(09596d8b-933e-4093-a627-78cef0237f46)'
    azureResourceGroup: 'my_resource'
    kubernetesCluster: 'newcluster'
    namespace: 'bermtec'
    command: 'install'
    chartType: 'Name'
    chartName: 'to-do'
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '4b53ffc7-25df-4b53-a750-c0a08f345e04'
  imageRepository: 'etikalanodetodo'
  containerRegistry: 'newacrr.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'newacrr19457d2e-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'Azure subscription 1(09596d8b-933e-4093-a627-78cef0237f46)'
    azureResourceGroup: 'my_resource'
    kubernetesCluster: 'newcluster'
    namespace: 'bermtec'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: 'Node-to-do'
