apiVersion: apps/v1
kind: Deployment 
metadata:
   name: my_deployment
spec:
   replicas: 2
   selectot: 
     matchlabels:
      app: my-app
   template:
     metadata:
      labels: 
        app: my-app
     spec:
      containers:
        - name: my-container
          image:  neeeacr.azurecr.io/ne-node:v2
          ports:
           - containerPort: 8000