apiVersion: apps/v1
kind: Deployment 
metadata:
   name: my-deployment
   namespace: bermtec
spec:
   replicas: 2
   selector: 
     matchLabels:
      app: my-app
   template:
     metadata:
      labels: 
        app: my-app
     spec:
      containers:
        - name: my-deployment
          image:  neeeacr.azurecr.io/ne-node:v2
          ports:
           - containerPort: 8000
      imagePullSecrets:
        - name: acr-secret