apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: bermtec
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-deployment
          image: newacrr.azurecr.io/mynewnode-to-do:1.0
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 60
      imagePullSecrets:
        - name: new-secret
