apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-network
spec:
  podSelector:
    matchLabels:
      app: my-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: my-role
    ports:
    - protocol: TCP
      port: 8000
