apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-rolebinding
  namespace: bermtec
subjects:
- kind: ServiceAccount
  name: my-serviceaccount
  namespace: bermtec
roleRef:
  kind: Role
  name: my-role
  apiGroup: rbac.authorization.k8s.io
